version: '3.2'

services:
  db:
    container_name: lucidboard_dev_db
    restart: always
    image: postgres
    volumes: [ "lucidboard_dev_db:/var/lib/postgresql/data" ]
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_PASSWORD: verysecure123

  app:
    container_name: lucidboard_dev
    restart: always
    build:
      context: .
      dockerfile: dev.Dockerfile
      args: { QL_MODE: "${QL_MODE}" }
    tty: true
    stdin_open: true
    depends_on: [ db ]
    volumes: [ ".:/app" ]
    ports: [ "8800:8800" ]
    environment:
      PG_HOST: db

volumes:
  lucidboard_dev_db:
